name: "Tests: E2E"
on: [pull_request]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: execute e2e tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:e2e